### PR TITLE
Unified agent log file name to mesos-agent.log, same as the Linux agent.

### PR DESCRIPTION
**Pull request by johnkord**
@ionutbalutoiu @yakman2020

### CODE REVIEW

**Comment by johnkord** [comment]
There were (erroneously) two agent log file names in the previous version of this file:  "mesos-service.err.log" and "mesos-slave.log".  There should only be one name for the log file, and I don't see a good reason it should be named anything other than what it is named on linux: mesos-agent.log

**Comment by johnkord** [comment]
Pinging @ionutbalutoiu for review

**Comment by ionutbalutoiu** [comment]
Hello John. The PR looks good. From our previous conversation, I think that we need to update the wrapper first, otherwise the `mesos-agent` won't be able to write to that file, right ?

Other than this, I think that we can merge.

**Comment by johnkord** [comment]
It turns out that what I mentioned yesterday isn’t a problem!  I was referring to making a change so that the flags that are passed to CreateFile() on line 170 of Program.cpp should change from “FILE_READ_DATA | FILE_WRITE_DATA” to “FILE_SHARE_READ | FILE_SHARE_WRITE”.  However, I did some research, and “FILE_READ_DATA” is #defined in the windows API to be the same number as “FILE_SHARE_READ”, so it would make no difference. (The same is true of the WRITE flags)

In the end, we found the bug to be within the mesos-agent itself.  You can change these flags if you want, I believe the “SHARE” flags are the ones expected in that parameter to CreateFile. But changing those flags should make no difference as to the behavior of the service wrapper, since they are numerically equivalent.

**Comment by ionutbalutoiu** [comment]
Ok. It makes sense. Thank-you for the clarifications.
Then everything looks good and we can merge this.
+1 from my side.

**Comment by ionutbalutoiu** [comment]
@yakman2020, @paulcallen feel free to approve the PR and merge. I don't have the rights to do it.

**Comment by yakman2020** [comment]
Done

**Comment by johnkord** [comment]
It turns out that what I mentioned yesterday isn’t a problem!  I was referring to making a change so that the flags that are passed to CreateFile() on line 170 of Program.cpp should change from “FILE_READ_DATA | FILE_WRITE_DATA” to “FILE_SHARE_READ | FILE_SHARE_WRITE”.  However, I did some research, and “FILE_READ_DATA” is #defined in the windows API to be the same number as “FILE_SHARE_READ”, so it would make no difference. (The same is true of the WRITE flags)

In the end, we found the bug to be within the mesos-agent itself.  You can change these flags if you want, I believe the “SHARE” flags are the ones expected in that parameter to CreateFile. But changing those flags should make no difference as to the behavior of the service wrapper, since they are numerically equivalent.

**Pull request merged**
